"""Added email field to User table

Revision ID: 3a9676e4f8a6
Revises: 
Create Date: 2025-02-28 16:37:29.453649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '3a9676e4f8a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True)) 
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    conn = op.get_bind()
    users = conn.execute(text("SELECT id, username FROM users")).fetchall()

    for user in users:
        unique_email = f"{user.username.lower().replace(' ', '_')}@example.com"
        conn.execute(text("UPDATE users SET email=:email WHERE id=:id"), {"email": unique_email, "id": user.id})

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column("email", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
